version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-network-api
    command: ["/wait-for-postgres.sh", "sh", "-c", "npm run migration:run && node -r dotenv/config dist/main.js"]
    ports:
      - "3000:3000"
    env_file:
      - ./environments/.env.dev
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: pg_container
    image: postgres
    restart: always
    env_file:
      - ./environments/.env.dev
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./environments/.env.dev
    ports:
      - "5050:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
